import { createSlice } from "@reduxjs/toolkit"

// authSlice is a Redux slice that manages the authentication 
// state of the application. It contains the initial state,
// reducers for setting and clearing the authentication token,
// and actions for logging out the user. The slice is used in 
// conjunction with the AuthListenerMiddleware to handle side 
// effects related to authentication, such as updating localStorage 
// and resetting the authApi state.


const authSlice = createSlice({
    name: "auth",
    initialState: {
        token: null,
        isAuthenticated: false
    },
    reducers: {
        // setToken reducer - sets the authentication token in the state
        // and marks the user as authenticated
        setToken: (state, action) => {
            state.token = action.payload,
            state.isAuthenticated = true
        },
        // setIsAuthenticated reducer - marks the user as authenticated
        setIsAuthenticated: (state) => {
            state.isAuthenticated = true
        },
        // clearToken reducer - clears the authentication token from the state
        // and marks the user as not authenticated
        clearToken: (state) => {
            state.token = null,
            state.isAuthenticated = false
        },
        // logOut reducer - almost same but different from clearToken 
        // because while it also removes the token from localStorage 
        // and resets the authApi state via a listener middleware
        logOut: (state) => {
            state.token = null,
            state.isAuthenticated = false
        }
    }
})


// export the actions generated by the authSlice for 
// use in components
export const {
    setToken,
    setIsAuthenticated,
    clearToken,
    logOut
} = authSlice.actions
export default authSlice.reducer