import { baseApi } from "../../../app/services/baseApi";

// booksApi is a service that provides endpoints for 
// fetching book data from the backend API. It uses 
// the baseApi service to define the endpoints and 
// their corresponding queries.

// define the booksApi service by injecting endpoints into
// the baseApi service
export const booksApi = baseApi.injectEndpoints({
    endpoints: function( builder ) {
        return {
            // getBookDetails endpoint - fetches the 
            // details of a specific book by its ID
            getBookDetails: builder.query({
                query: function( id ) {
                    return `/books/${id}`
                }
            }),
            // getBooks endpoint - fetches a list of books
            // with pagination support
            getBooks: builder.query({
                query: function( page ) {
                    return {
                        url: "/books",
                        params: {
                            page
                        }
                    }
                }
            }),
            // searchBooks endpoint - fetches a list of books
            // that match the search query
            searchBooks: builder.query({
                query: function( query ) {
                    return {
                        url: "/books/search",
                        params: {
                            query
                        }
                    }
                }
            })
        }
    }
})

// export the hooks generated by the booksApi service for
// each endpoint. These hooks can be used in React components
// to fetch data and manage loading and error states.
export const {
    useGetBookDetailsQuery,
    useGetBooksQuery,
    useSearchBooksQuery
} = booksApi