import { baseApi } from "../../../app/services/baseApi.js"

// authApi is a service that provides endpoints for 
// user authentication and profile management. It uses 
// the baseApi service to define the endpoints and 
// their corresponding queries and mutations.

export const authApi = baseApi.injectEndpoints({
    endpoints: function( builder ) {
        return {
            // googleVerify endpoint - verifies the Google sign-in credentials
            // and returns the authentication status and user data
            googleVerify: builder.query({
                query: ( id ) => ({
                    url: "/auth/google/verify",
                    params: {
                        authId: id
                    }
                })
            }),
            // getMe endpoint - fetches the authenticated user's profile data
            // provides a "user" tag for cache invalidation
            getMe: builder.query({
                query: () => "/auth/me",
                providesTags: ["user"]
            }),
            // logout endpoint - logs the user out of the application
            // does not require any parameters and returns a success message
            logout: builder.mutation({
                query: () => ({
                    url: "/auth/logout",
                    method: "GET"
                })
            }),
            // updateUser endpoint - updates the authenticated user's profile data
            // accepts name, photo, and delete_photo parameters and 
            // returns the updated user data
            updateUser: builder.mutation({
                query: function({ name, photo, delete_photo = false }) {
                    let newUserInfo = new FormData()

                    if ( name ) newUserInfo.append("name", name)
                    if ( photo ) newUserInfo.append("photo", photo)

                    return {
                        url: `/auth/update?deletePhoto=${ delete_photo }`,
                        method: "POST",
                        body: newUserInfo
                    }
                },
                invalidatesTags: ["user"]
            })
        }
    }
})


// export the hooks generated by the authApi service for
// each endpoint. These hooks can be used in React components
// to fetch data, perform mutations, and manage loading and error states.
export const {
    useGoogleVerifyQuery,
    useGetMeQuery,
    useLogoutMutation,
    useUpdateUserMutation
} = authApi